server {
  listen 80 default_server;
  server_name localhost php85.localhost;
  root /var/www/php8/public;
  index index.php index.html;
  location / { try_files $uri $uri/ /index.php?$query_string; }
  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass php8:9000;
  }
}

server {
  listen 80;
  server_name php81.localhost;
  root /var/www/php81/public;
  index index.php index.html;
  location / { try_files $uri $uri/ /index.php?$query_string; }
  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass php81:9000;
  }
}

server {
  listen 80;
  server_name php71.localhost;
  root /var/www/php71/public;
  index index.php index.html;
  location / { try_files $uri $uri/ /index.php?$query_string; }
  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass php71:9000;
  }
}

server {
  listen 80;
  server_name php53.localhost;
  root /var/www/php53/public;
  index index.php index.html;
  location / { try_files $uri $uri/ /index.php?$query_string; }
  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass php53:9000;
  }
}
