server {
  listen 80 default_server;
  server_name localhost php85.localhost;
  root /var/www/php8/public;
  index index.php index.html;
  resolver 127.0.0.11 ipv6=off valid=10s;
  set $php_upstream php-fpm-8.5;
  location / { try_files $uri $uri/ /index.php?$query_string; }
  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass $php_upstream:9000;
  }
}

server {
  listen 80;
  server_name php81.localhost;
  root /var/www/php81/public;
  index index.php index.html;
  resolver 127.0.0.11 ipv6=off valid=10s;
  set $php_upstream php-fpm-8.1;
  location / { try_files $uri $uri/ /index.php?$query_string; }
  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass $php_upstream:9000;
  }
}

server {
  listen 80;
  server_name php71.localhost;
  root /var/www/php71/public;
  index index.php index.html;
  resolver 127.0.0.11 ipv6=off valid=10s;
  set $php_upstream php-fpm-7.1;
  location / { try_files $uri $uri/ /index.php?$query_string; }
  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass $php_upstream:9000;
  }
}

server {
  listen 80;
  server_name php53.localhost;
  root /var/www/php53/public;
  index index.php index.html;
  resolver 127.0.0.11 ipv6=off valid=10s;
  set $php_upstream php-fpm-5.3;
  location / { try_files $uri $uri/ /index.php?$query_string; }
  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass $php_upstream:9000;
  }
}

server {
  listen 80;
  server_name php56.localhost;
  root /var/www/php56/public;
  index index.php index.html;
  resolver 127.0.0.11 ipv6=off valid=10s;
  set $php_upstream php-fpm-5.6;
  location / { try_files $uri $uri/ /index.php?$query_string; }
  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_pass $php_upstream:9000;
  }
}
